---
services: docker

env:
  - distro: centos7
  - distro: fedora27

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim
  - wget -O ${PWD}/tests/test.sh https://gist.github.com/brentwg/64f90bdda32a51360f71558d3171fcbb/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests
  - ${PWD}/tests/test.sh

  # Test whether Docker is running correctly (Dockerception!).
  - docker exec --tty ${container_id} docker run hello-world

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
