---
- name: Ensure old versions of Docker are not installed (Debian)
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Ensure depdencies are installed (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Copy the Docker REPO file (Debian)
  copy:
    src: files/docker.list
    dest: /etc/apt/sources.list.d/docker.list
  register: dockerrepofile

- name: Add the GPG key for the official Docker repository
  shell: |
    curl -fsSL {{ docker_gpg_key_url }} | sudo apt-key add -
    sudo apt-get update
  args:
    executable: /bin/bash
  when: dockerrepofile.changed
