---
- name: Uninstall old version of Docker (RHEL)
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
