---
- name: Ensure old versions of Docker are not installed (Debian)
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Ensure depdencies are installed (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add Docker apt key (Debian)
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: no

- name: Add Docker repository (Debian)
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes
